# Generated by Django 3.0.6 on 2020-05-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, default='none', upload_to='media/'),
        ),
    ]
