# Generated by Django 3.0.6 on 2020-05-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20200518_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
